import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "API Reference – Reev Docs",
  description:
    "REST API endpoints for events, reports, patterns, flows, and suggestions.",
};

function Endpoint({
  method,
  path,
  auth,
  desc,
  children,
}: {
  method: string;
  path: string;
  auth: "none" | "session" | "api-key";
  desc: string;
  children?: React.ReactNode;
}) {
  const methodColor: Record<string, string> = {
    GET: "text-green-400 bg-green-500/10",
    POST: "text-blue-400 bg-blue-500/10",
    PUT: "text-yellow-400 bg-yellow-500/10",
    PATCH: "text-purple-400 bg-purple-500/10",
    DELETE: "text-red-400 bg-red-500/10",
  };

  return (
    <div className="border border-zinc-800 mb-4">
      <div className="flex items-center gap-3 px-4 py-3 bg-zinc-900/50 border-b border-zinc-800">
        <span
          className={`text-[10px] font-bold px-2 py-0.5 ${methodColor[method] || "text-zinc-400 bg-zinc-800"}`}
        >
          {method}
        </span>
        <code className="text-sm text-zinc-200 font-mono">{path}</code>
        {auth === "none" && (
          <span className="text-[10px] text-zinc-600 ml-auto">Public</span>
        )}
        {auth === "session" && (
          <span className="text-[10px] text-orange-400/70 ml-auto">
            Auth required
          </span>
        )}
      </div>
      <div className="px-4 py-3">
        <p className="text-xs text-zinc-400 mb-2">{desc}</p>
        {children}
      </div>
    </div>
  );
}

function ParamTable({
  params,
}: {
  params: { name: string; type: string; required: boolean; desc: string }[];
}) {
  return (
    <table className="w-full text-left mt-2 mb-1">
      <thead>
        <tr className="border-b border-zinc-800">
          <th className="pb-1.5 text-[10px] font-semibold text-zinc-500">
            Param
          </th>
          <th className="pb-1.5 text-[10px] font-semibold text-zinc-500">
            Type
          </th>
          <th className="pb-1.5 text-[10px] font-semibold text-zinc-500">
            Description
          </th>
        </tr>
      </thead>
      <tbody>
        {params.map((p) => (
          <tr key={p.name} className="border-b border-zinc-800/50">
            <td className="py-1.5 pr-3 align-top">
              <code className="text-orange-400 text-xs">{p.name}</code>
              {p.required && (
                <span className="text-red-400 text-[10px] ml-1">*</span>
              )}
            </td>
            <td className="py-1.5 pr-3 align-top text-xs text-zinc-500 font-mono">
              {p.type}
            </td>
            <td className="py-1.5 align-top text-xs text-zinc-400">
              {p.desc}
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

export default function ApiReferencePage() {
  return (
    <>
      <h1 className="text-2xl font-bold text-white mb-2">API Reference</h1>
      <p className="text-zinc-400 mb-8">
        All endpoints are relative to your Reev instance URL. Authenticated
        endpoints require a valid session cookie.
      </p>

      {/* Events */}
      <section className="mb-10">
        <h2 className="text-lg font-semibold text-white mb-4">Events</h2>
        <p className="text-sm text-zinc-400 mb-4">
          The tracker sends batched events to this endpoint. It is public
          (no session required) but rate-limited to 60 requests/minute per IP.
        </p>

        <Endpoint
          method="POST"
          path="/api/events"
          auth="none"
          desc="Ingest a batch of tracker events."
        >
          <ParamTable
            params={[
              {
                name: "sessionId",
                type: "string",
                required: true,
                desc: "Unique session ID generated by the tracker.",
              },
              {
                name: "projectId",
                type: "string",
                required: true,
                desc: "Your project ID.",
              },
              {
                name: "events",
                type: "array",
                required: true,
                desc: "Array of event objects (max 50 per batch).",
              },
            ]}
          />
          <p className="text-xs text-zinc-500 mt-2">
            Valid event types:{" "}
            <code className="text-zinc-400">
              pageview, click, scroll, form, error, vitals, page_leave,
              ux_issue, ux_feedback, suggestion_clicked, suggestion_dismissed
            </code>
          </p>
          <p className="text-xs text-zinc-500 mt-1">
            Returns <code className="text-zinc-400">204</code> on success. Max
            payload: 512 KB.
          </p>
        </Endpoint>
      </section>

      {/* Reports */}
      <section className="mb-10">
        <h2 className="text-lg font-semibold text-white mb-4">Reports</h2>
        <p className="text-sm text-zinc-400 mb-4">
          UX feedback reports collected from popover responses.
        </p>

        <Endpoint
          method="GET"
          path="/api/reports"
          auth="session"
          desc="List feedback reports for a project."
        >
          <ParamTable
            params={[
              {
                name: "projectId",
                type: "string",
                required: true,
                desc: "Project ID.",
              },
              {
                name: "status",
                type: "string",
                required: false,
                desc: '"open" (default), "resolved", or "all".',
              },
              {
                name: "issueType",
                type: "string",
                required: false,
                desc: "Filter by issue type (rage_click, dead_link, etc.).",
              },
              {
                name: "search",
                type: "string",
                required: false,
                desc: "Search in message and page URL.",
              },
              {
                name: "limit",
                type: "number",
                required: false,
                desc: "Page size (default 20).",
              },
              {
                name: "offset",
                type: "number",
                required: false,
                desc: "Pagination offset.",
              },
            ]}
          />
        </Endpoint>

        <Endpoint
          method="PATCH"
          path="/api/reports"
          auth="session"
          desc="Update a report's status."
        >
          <ParamTable
            params={[
              {
                name: "id",
                type: "number",
                required: true,
                desc: "Report ID.",
              },
              {
                name: "status",
                type: "string",
                required: true,
                desc: '"open" or "resolved".',
              },
            ]}
          />
        </Endpoint>
      </section>

      {/* Patterns */}
      <section className="mb-10">
        <h2 className="text-lg font-semibold text-white mb-4">Patterns</h2>
        <p className="text-sm text-zinc-400 mb-4">
          Automatically detected recurring UX issue patterns.
        </p>

        <Endpoint
          method="GET"
          path="/api/patterns"
          auth="session"
          desc="List detected patterns for a project."
        >
          <ParamTable
            params={[
              {
                name: "projectId",
                type: "string",
                required: true,
                desc: "Project ID.",
              },
              {
                name: "status",
                type: "string",
                required: false,
                desc: '"open" (default), "resolved", or "all".',
              },
              {
                name: "issueType",
                type: "string",
                required: false,
                desc: "Filter by issue type.",
              },
              {
                name: "limit",
                type: "number",
                required: false,
                desc: "Page size (default 20).",
              },
              {
                name: "offset",
                type: "number",
                required: false,
                desc: "Pagination offset.",
              },
            ]}
          />
        </Endpoint>

        <Endpoint
          method="PATCH"
          path="/api/patterns"
          auth="session"
          desc="Update a pattern's status. Also bulk-updates linked reports."
        >
          <ParamTable
            params={[
              {
                name: "id",
                type: "number",
                required: true,
                desc: "Pattern ID.",
              },
              {
                name: "status",
                type: "string",
                required: true,
                desc: '"open" or "resolved".',
              },
            ]}
          />
        </Endpoint>
      </section>

      {/* Flows */}
      <section className="mb-10">
        <h2 className="text-lg font-semibold text-white mb-4">
          Flow Suggestions
        </h2>
        <p className="text-sm text-zinc-400 mb-4">
          Manage navigation suggestions shown in the on-site widget.
        </p>

        <Endpoint
          method="GET"
          path="/api/flows"
          auth="session"
          desc="List all flow suggestions for a project."
        >
          <ParamTable
            params={[
              {
                name: "projectId",
                type: "string",
                required: true,
                desc: "Project ID.",
              },
              {
                name: "source",
                type: "string",
                required: false,
                desc: 'Filter by source: "manual", "auto", or "sitemap".',
              },
            ]}
          />
        </Endpoint>

        <Endpoint
          method="POST"
          path="/api/flows"
          auth="session"
          desc="Create a flow suggestion."
        >
          <ParamTable
            params={[
              {
                name: "projectId",
                type: "string",
                required: true,
                desc: "Project ID.",
              },
              {
                name: "sourceUrlPattern",
                type: "string",
                required: true,
                desc: "URL pattern where the suggestion appears.",
              },
              {
                name: "targetUrl",
                type: "string",
                required: true,
                desc: "URL the suggestion links to.",
              },
              {
                name: "targetLabel",
                type: "string",
                required: true,
                desc: "Display label for the suggestion.",
              },
              {
                name: "priority",
                type: "number",
                required: false,
                desc: "Sort priority (default 10).",
              },
            ]}
          />
        </Endpoint>

        <Endpoint
          method="PUT"
          path="/api/flows"
          auth="session"
          desc="Update a flow suggestion."
        >
          <ParamTable
            params={[
              {
                name: "id",
                type: "number",
                required: true,
                desc: "Suggestion ID.",
              },
              {
                name: "targetLabel",
                type: "string",
                required: false,
                desc: "New label.",
              },
              {
                name: "priority",
                type: "number",
                required: false,
                desc: "New priority.",
              },
              {
                name: "isActive",
                type: "boolean",
                required: false,
                desc: "Enable or disable.",
              },
            ]}
          />
        </Endpoint>

        <Endpoint
          method="DELETE"
          path="/api/flows?id={id}"
          auth="session"
          desc="Delete a flow suggestion."
        >
          <ParamTable
            params={[
              {
                name: "id",
                type: "number",
                required: true,
                desc: "Suggestion ID (query param).",
              },
            ]}
          />
        </Endpoint>
      </section>

      {/* Flow Config */}
      <section className="mb-10">
        <h2 className="text-lg font-semibold text-white mb-4">Flow Config</h2>

        <Endpoint
          method="GET"
          path="/api/flows/config"
          auth="session"
          desc="Get the flow widget configuration for a project."
        >
          <ParamTable
            params={[
              {
                name: "projectId",
                type: "string",
                required: true,
                desc: "Project ID.",
              },
            ]}
          />
        </Endpoint>

        <Endpoint
          method="PUT"
          path="/api/flows/config"
          auth="session"
          desc="Update flow widget configuration."
        >
          <ParamTable
            params={[
              {
                name: "projectId",
                type: "string",
                required: true,
                desc: "Project ID.",
              },
              {
                name: "enabled",
                type: "boolean",
                required: false,
                desc: "Enable or disable the widget.",
              },
              {
                name: "displayMode",
                type: "string",
                required: false,
                desc: '"frustration" or "always".',
              },
              {
                name: "maxSuggestions",
                type: "number",
                required: false,
                desc: "Max suggestions to show.",
              },
              {
                name: "widgetPosition",
                type: "string",
                required: false,
                desc: '"bottom-right" or "bottom-left".',
              },
              {
                name: "widgetTheme",
                type: "string",
                required: false,
                desc: '"dark" or "light".',
              },
              {
                name: "autoDiscover",
                type: "boolean",
                required: false,
                desc: "Auto-generate suggestions from navigation patterns.",
              },
            ]}
          />
        </Endpoint>
      </section>

      {/* Suggest */}
      <section className="mb-10">
        <h2 className="text-lg font-semibold text-white mb-4">
          Suggest (Tracker)
        </h2>
        <p className="text-sm text-zinc-400 mb-4">
          Public endpoint called by the on-site widget to fetch suggestions for
          the current page.
        </p>

        <Endpoint
          method="GET"
          path="/api/flows/suggest"
          auth="none"
          desc="Get active suggestions for a page. Rate-limited to 30 req/min per IP."
        >
          <ParamTable
            params={[
              {
                name: "projectId",
                type: "string",
                required: true,
                desc: "Project ID.",
              },
              {
                name: "url",
                type: "string",
                required: true,
                desc: "Current page URL.",
              },
            ]}
          />
          <p className="text-xs text-zinc-500 mt-2">
            Returns all active suggestions sorted by relevance to the current
            path. Excludes the current page from results.
          </p>
        </Endpoint>
      </section>

      {/* Bulk */}
      <section>
        <h2 className="text-lg font-semibold text-white mb-4">Bulk Import</h2>

        <Endpoint
          method="POST"
          path="/api/flows/bulk"
          auth="session"
          desc="Create multiple flow suggestions in one request (max 50)."
        >
          <ParamTable
            params={[
              {
                name: "projectId",
                type: "string",
                required: true,
                desc: "Project ID.",
              },
              {
                name: "suggestions",
                type: "array",
                required: true,
                desc: "Array of { sourceUrlPattern, targetUrl, targetLabel, priority? }.",
              },
            ]}
          />
        </Endpoint>

        <Endpoint
          method="GET"
          path="/api/flows/sitemap"
          auth="session"
          desc="Fetch and parse the project's sitemap.xml into a tree structure."
        >
          <ParamTable
            params={[
              {
                name: "projectId",
                type: "string",
                required: true,
                desc: "Project ID. The project must have a website_url configured.",
              },
            ]}
          />
        </Endpoint>
      </section>
    </>
  );
}
